import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'vi' | 'en';

interface Translations {
  vi: Record<string, string>;
  en: Record<string, string>;
}

const translations: Translations = {
  vi: {
    appTitle: 'Smart Parking',
    university: 'ĐH Bách Khoa TP.HCM',
    dashboard: 'Tổng quan',
    parking: 'Bãi xe',
    transactions: 'Giao dịch',
    settings: 'Cài đặt',
    admin: 'Quản trị',
    available: 'Còn trống',
    occupied: 'Đã đậu',
    total: 'Tổng',
    parkingLot: 'Bãi',
    location: 'Vị trí',
    capacity: 'Sức chứa',
    status: 'Trạng thái',
    spots: 'chỗ',
    lotA: 'Bãi A',
    lotB: 'Bãi B',
    lotC: 'Bãi C',
    lotD: 'Bãi D',
    buildingH1: 'Tòa H1',
    buildingH6: 'Tòa H6',
    realTimeStatus: 'Trạng thái bãi xe',
    todayStats: 'Hôm nay',
    vehicles: 'Lượt xe',
    revenue: 'Doanh thu',
    occupancyRate: 'Lấp đầy',
    viewDetails: 'Chi tiết',
    recentTransactions: 'Giao dịch gần đây',
    time: 'Thời gian',
    user: 'Người dùng',
    amount: 'Số tiền',
    entryTime: 'Vào',
    exitTime: 'Ra',
    duration: 'Thời lượng',
    quickActions: 'Thao tác nhanh',
    issueTemporaryTicket: 'Phát vé tạm',
    viewReports: 'Báo cáo',
    manageUsers: 'Người dùng',
    configurePricing: 'Cấu hình giá',
    systemHealth: 'Trạng thái hệ thống',
    allSensorsOnline: 'Cảm biến hoạt động',
    normal: 'Bình thường',
    nearlyFull: 'Gần đầy',
    full: 'Đầy',
    scanCard: 'Quét thẻ',
    scanCardEntry: 'Quét thẻ ra/vào',
    studentId: 'MSSV/MSNV',
    name: 'Họ tên',
    role: 'Vai trò',
    student: 'Sinh viên',
    lecturer: 'Giảng viên',
    staff: 'Nhân viên',
    visitor: 'Khách',
    enterNow: 'Vào bãi xe',
    exitNow: 'Ra khỏi bãi',
    payment: 'Thanh toán',
    myTransactions: 'Giao dịch của tôi',
    monthlyBilling: 'Hóa đơn tháng',
    pending: 'Chờ xử lý',
    paid: 'Đã thanh toán',
    failed: 'Thất bại',
    payNow: 'Thanh toán ngay',
    totalAmount: 'Tổng tiền',
    trips: 'lượt',
    thisMonth: 'Tháng này',
    lastMonth: 'Tháng trước',
    temporaryTicket: 'Vé tạm',
    issueTicket: 'Phát vé',
    ticketNumber: 'Số vé',
    issueTime: 'Giờ phát',
    validUntil: 'Hiệu lực đến',
    printTicket: 'In vé',
    chart: 'Biểu đồ',
    hourly: 'Theo giờ',
    daily: 'Theo ngày',
    weekly: 'Theo tuần',
    monthly: 'Theo tháng',
    occupancyTrend: 'xu hướng lấp đầy',
    revenueTrend: 'xu hướng doanh thu',
    language: 'Ngôn ngữ',
    notifications: 'Thông báo',
    profile: 'Hồ sơ',
    help: 'Trợ giúp',
    logout: 'Đăng xuất',
    welcome: 'Xin chào',
    selectLot: 'Chọn bãi xe',
    selectAction: 'Chọn thao tác',
    entry: 'Vào',
    exit: 'Ra',
    cardAccepted: 'Thẻ hợp lệ',
    cardRejected: 'Thẻ không hợp lệ',
    noSpaceAvailable: 'Hết chỗ đậu',
    gateOpening: 'Đang mở cổng...',
    success: 'Thành công',
    error: 'Lỗi',
  },
  en: {
    appTitle: 'Smart Parking',
    university: 'HCMUT',
    dashboard: 'Dashboard',
    parking: 'Parking',
    transactions: 'Transactions',
    settings: 'Settings',
    admin: 'Admin',
    available: 'Available',
    occupied: 'Occupied',
    total: 'Total',
    parkingLot: 'Lot',
    location: 'Location',
    capacity: 'Capacity',
    status: 'Status',
    spots: 'spots',
    lotA: 'Lot A',
    lotB: 'Lot B',
    lotC: 'Lot C',
    lotD: 'Lot D',
    buildingH1: 'Building H1',
    buildingH6: 'Building H6',
    realTimeStatus: 'Parking Status',
    todayStats: 'Today',
    vehicles: 'Vehicles',
    revenue: 'Revenue',
    occupancyRate: 'Occupancy',
    viewDetails: 'Details',
    recentTransactions: 'Recent Transactions',
    time: 'Time',
    user: 'User',
    amount: 'Amount',
    entryTime: 'In',
    exitTime: 'Out',
    duration: 'Duration',
    quickActions: 'Quick Actions',
    issueTemporaryTicket: 'Issue Temp Ticket',
    viewReports: 'Reports',
    manageUsers: 'Users',
    configurePricing: 'Pricing',
    systemHealth: 'System Status',
    allSensorsOnline: 'Sensors Online',
    normal: 'Normal',
    nearlyFull: 'Nearly Full',
    full: 'Full',
    scanCard: 'Scan Card',
    scanCardEntry: 'Card Entry/Exit',
    studentId: 'ID Number',
    name: 'Name',
    role: 'Role',
    student: 'Student',
    lecturer: 'Lecturer',
    staff: 'Staff',
    visitor: 'Visitor',
    enterNow: 'Enter Parking',
    exitNow: 'Exit Parking',
    payment: 'Payment',
    myTransactions: 'My Transactions',
    monthlyBilling: 'Monthly Bill',
    pending: 'Pending',
    paid: 'Paid',
    failed: 'Failed',
    payNow: 'Pay Now',
    totalAmount: 'Total',
    trips: 'trips',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    temporaryTicket: 'Temp Ticket',
    issueTicket: 'Issue Ticket',
    ticketNumber: 'Ticket No.',
    issueTime: 'Issue Time',
    validUntil: 'Valid Until',
    printTicket: 'Print Ticket',
    chart: 'Chart',
    hourly: 'Hourly',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    occupancyTrend: 'occupancy trend',
    revenueTrend: 'revenue trend',
    language: 'Language',
    notifications: 'Notifications',
    profile: 'Profile',
    help: 'Help',
    logout: 'Logout',
    welcome: 'Welcome',
    selectLot: 'Select Lot',
    selectAction: 'Select Action',
    entry: 'Entry',
    exit: 'Exit',
    cardAccepted: 'Card Accepted',
    cardRejected: 'Card Rejected',
    noSpaceAvailable: 'No Space',
    gateOpening: 'Opening Gate...',
    success: 'Success',
    error: 'Error',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('vi');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
