import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'vi' | 'en';

interface Translations {
  vi: Record<string, string>;
  en: Record<string, string>;
}

const translations: Translations = {
  vi: {
    appTitle: 'Smart Parking',
    university: 'ĐH Bách Khoa TP.HCM',
    dashboard: 'Tổng quan',
    parking: 'Bãi xe',
    transactions: 'Giao dịch',
    settings: 'Cài đặt',
    admin: 'Quản trị',
    available: 'Còn trống',
    occupied: 'Đã đậu',
    total: 'Tổng',
    parkingLot: 'Bãi',
    location: 'Vị trí',
    capacity: 'Sức chứa',
    status: 'Trạng thái',
    spots: 'chỗ',
    lotA: 'Bãi A',
    lotB: 'Bãi B',
    lotC: 'Bãi C',
    lotD: 'Bãi D',
    buildingH1: 'Tòa H1',
    buildingH6: 'Tòa H6',
    realTimeStatus: 'Trạng thái bãi xe',
    todayStats: 'Hôm nay',
    vehicles: 'Lượt xe',
    revenue: 'Doanh thu',
    occupancyRate: 'Lấp đầy',
    viewDetails: 'Chi tiết',
    recentTransactions: 'Giao dịch gần đây',
    time: 'Thời gian',
    user: 'Người dùng',
    amount: 'Số tiền',
    entryTime: 'Vào',
    exitTime: 'Ra',
    duration: 'Thời lượng',
    quickActions: 'Thao tác nhanh',
    issueTemporaryTicket: 'Phát vé tạm',
    viewReports: 'Báo cáo',
    manageUsers: 'Người dùng',
    configurePricing: 'Cấu hình giá',
    systemHealth: 'Trạng thái hệ thống',
    allSensorsOnline: 'Cảm biến hoạt động',
    normal: 'Bình thường',
    nearlyFull: 'Gần đầy',
    full: 'Đầy',
    scanCard: 'Quét thẻ',
    scanCardEntry: 'Quét thẻ ra/vào',
    studentId: 'MSSV/MSNV',
    name: 'Họ tên',
    role: 'Vai trò',
    student: 'Sinh viên',
    lecturer: 'Giảng viên',
    staff: 'Nhân viên',
    visitor: 'Khách',
    enterNow: 'Vào bãi xe',
    exitNow: 'Ra khỏi bãi',
    payment: 'Thanh toán',
    myTransactions: 'Giao dịch của tôi',
    monthlyBilling: 'Hóa đơn tháng',
    pending: 'Chờ xử lý',
    paid: 'Đã thanh toán',
    failed: 'Thất bại',
    payNow: 'Thanh toán ngay',
    totalAmount: 'Tổng tiền',
    trips: 'lượt',
    thisMonth: 'Tháng này',
    lastMonth: 'Tháng trước',
    temporaryTicket: 'Vé tạm',
    issueTicket: 'Phát vé',
    ticketNumber: 'Số vé',
    issueTime: 'Giờ phát',
    validUntil: 'Hiệu lực đến',
    printTicket: 'In vé',
    chart: 'Biểu đồ',
    hourly: 'Theo giờ',
    daily: 'Theo ngày',
    weekly: 'Theo tuần',
    monthly: 'Theo tháng',
    occupancyTrend: 'xu hướng lấp đầy',
    revenueTrend: 'xu hướng doanh thu',
    language: 'Ngôn ngữ',
    notifications: 'Thông báo',
    profile: 'Hồ sơ',
    help: 'Trợ giúp',
    logout: 'Đăng xuất',
    welcome: 'Xin chào',
    selectLot: 'Chọn bãi xe',
    selectAction: 'Chọn thao tác',
    entry: 'Vào',
    exit: 'Ra',
    cardAccepted: 'Thẻ hợp lệ',
    cardRejected: 'Thẻ không hợp lệ',
    noSpaceAvailable: 'Hết chỗ đậu',
    gateOpening: 'Đang mở cổng...',
    success: 'Thành công',
    error: 'Lỗi',
    thousand: 'nghìn',
    ticketinfo: 'Thông tin thẻ',
    due: 'Hạn thanh toán',
    parkingtripdetails: 'Chi tiết lượt gửi xe',
    // Bổ sung các key mới từ SettingScreen
    configurePricingDesc: 'Cấu hình chính sách giá cho từng đối tượng',
    pricingByTarget: 'Giá gửi xe theo đối tượng',
    studentDesc: 'Sinh viên, học viên, nghiên cứu sinh',
    periodic: 'Định kỳ',
    vndPerDay: '₫/ngày',
    lecturerDesc: 'Giảng viên',
    free: 'Miễn phí',
    staffDesc: 'Cán bộ, nhân viên',
    visitorDesc: 'Khách vãng lai',
    byHour: 'Theo giờ',
    vndPerHour: '₫/giờ',
    note: 'Lưu ý',
    pricingNoteDesc: 'Thay đổi chính sách giá sẽ được áp dụng từ chu kỳ thanh toán tiếp theo. Chu kỳ hiện tại vẫn giữ nguyên mức giá cũ.',
    saveConfig: 'Lưu cấu hình',
    saveConfigSuccess: 'Đã lưu cấu hình giá thành công!',
    syncData: 'Đồng bộ dữ liệu',
    syncDataDesc: 'Đồng bộ thông tin từ HCMUT_DATACORE',
    centralDataSystem: 'Hệ thống dữ liệu trung tâm',
    syncingData: 'Đang đồng bộ dữ liệu...',
    syncSuccess: 'Đồng bộ thành công!',
    updated: 'Đã cập nhật',
    records: 'bản ghi',
    syncNow: 'Đồng bộ ngay',
    syncHistory: 'Lịch sử đồng bộ',
    auto: 'Tự động',
    readOnlyMode: 'Chế độ chỉ đọc',
    readOnlyDesc: 'Hệ thống chỉ có quyền đọc dữ liệu từ DATACORE. Không thể chỉnh sửa thông tin người dùng.',
    studentIdOnly: 'MSSV',
    faculty: 'Khoa',
    email: 'Email',
    bkpayAccount: 'Tài khoản BKPay',
    linked: 'Đã liên kết',
    cseFaculty: 'Khoa Khoa học & Kỹ thuật Máy tính',
    settingsDesc: 'Cấu hình và quản trị hệ thống',
    profileDesc: 'Thông tin cá nhân',
    pricingPolicyDesc: 'Chính sách giá gửi xe',
    notificationsDesc: 'Quản lý thông báo',
    helpDesc: 'Hướng dẫn sử dụng',
    scantogoin: 'Quét thẻ để vào bãi xe',
    scantogoout: 'Quét thẻ để ra khỏi bãi xe',
    forguests: 'Dành cho khách vãng lai',
  },
  en: {
    appTitle: 'Smart Parking',
    university: 'HCMUT',
    dashboard: 'Dashboard',
    parking: 'Parking',
    transactions: 'Transactions',
    settings: 'Settings',
    admin: 'Admin',
    available: 'Available',
    occupied: 'Occupied',
    total: 'Total',
    parkingLot: 'Lot',
    location: 'Location',
    capacity: 'Capacity',
    status: 'Status',
    spots: 'spots',
    lotA: 'Lot A',
    lotB: 'Lot B',
    lotC: 'Lot C',
    lotD: 'Lot D',
    buildingH1: 'Building H1',
    buildingH6: 'Building H6',
    realTimeStatus: 'Parking Status',
    todayStats: 'Today',
    vehicles: 'Vehicles',
    revenue: 'Revenue',
    occupancyRate: 'Occupancy',
    viewDetails: 'Details',
    recentTransactions: 'Recent Transactions',
    time: 'Time',
    user: 'User',
    amount: 'Amount',
    entryTime: 'In',
    exitTime: 'Out',
    duration: 'Duration',
    quickActions: 'Quick Actions',
    issueTemporaryTicket: 'Issue Temp Ticket',
    viewReports: 'Reports',
    manageUsers: 'Users',
    configurePricing: 'Pricing',
    systemHealth: 'System Status',
    allSensorsOnline: 'Sensors Online',
    normal: 'Normal',
    nearlyFull: 'Nearly Full',
    full: 'Full',
    scanCard: 'Scan Card',
    scanCardEntry: 'Card Entry/Exit',
    studentId: 'ID Number',
    name: 'Name',
    role: 'Role',
    student: 'Student',
    lecturer: 'Lecturer',
    staff: 'Staff',
    visitor: 'Visitor',
    enterNow: 'Enter Parking',
    exitNow: 'Exit Parking',
    payment: 'Payment',
    myTransactions: 'My Transactions',
    monthlyBilling: 'Monthly Bill',
    pending: 'Pending',
    paid: 'Paid',
    failed: 'Failed',
    payNow: 'Pay Now',
    totalAmount: 'Total',
    trips: 'trips',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    temporaryTicket: 'Temp Ticket',
    issueTicket: 'Issue Ticket',
    ticketNumber: 'Ticket No.',
    issueTime: 'Issue Time',
    validUntil: 'Valid Until',
    printTicket: 'Print Ticket',
    chart: 'Chart',
    hourly: 'Hourly',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    occupancyTrend: 'occupancy trend',
    revenueTrend: 'revenue trend',
    language: 'Language',
    notifications: 'Notifications',
    profile: 'Profile',
    help: 'Help',
    logout: 'Logout',
    welcome: 'Welcome',
    selectLot: 'Select Lot',
    selectAction: 'Select Action',
    entry: 'Entry',
    exit: 'Exit',
    cardAccepted: 'Card Accepted',
    cardRejected: 'Card Rejected',
    noSpaceAvailable: 'No Space',
    gateOpening: 'Opening Gate...',
    success: 'Success',
    error: 'Error',
    thousand: 'thousand',
    ticketinfo: 'Ticket Information',
    due: 'Due Date',
    parkingtripdetails: 'Parking Trip Details',
    // Bổ sung các key mới từ SettingScreen
    configurePricingDesc: 'Configure pricing policy for each target group',
    pricingByTarget: 'Parking fee by target group',
    studentDesc: 'Students, trainees, postgraduates',
    periodic: 'Periodic',
    vndPerDay: '₫/day',
    lecturerDesc: 'Lecturers',
    free: 'Free',
    staffDesc: 'Staff, employees',
    visitorDesc: 'Visitors',
    byHour: 'Hourly',
    vndPerHour: '₫/hour',
    note: 'Note',
    pricingNoteDesc: 'Pricing policy changes will be applied from the next billing cycle. The current cycle retains the old price.',
    saveConfig: 'Save configuration',
    saveConfigSuccess: 'Pricing configuration saved successfully!',
    syncData: 'Sync Data',
    syncDataDesc: 'Sync information from HCMUT_DATACORE',
    centralDataSystem: 'Central data system',
    syncingData: 'Syncing data...',
    syncSuccess: 'Sync successful!',
    updated: 'Updated',
    records: 'records',
    syncNow: 'Sync now',
    syncHistory: 'Sync history',
    auto: 'Auto',
    readOnlyMode: 'Read-only mode',
    readOnlyDesc: 'The system only has read access from DATACORE. User information cannot be edited.',
    studentIdOnly: 'Student ID',
    faculty: 'Faculty',
    email: 'Email',
    bkpayAccount: 'BKPay Account',
    linked: 'Linked',
    cseFaculty: 'Faculty of Computer Science & Engineering',
    settingsDesc: 'System configuration and administration',
    profileDesc: 'Personal information',
    pricingPolicyDesc: 'Parking pricing policy',
    notificationsDesc: 'Manage notifications',
    helpDesc: 'User manual',
    scantogoin: 'Scan card to enter parking',
    scantogoout: 'Scan card to exit parking',
    forguests: 'For guests',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('vi');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}